name: CI
on: [push, pull_request]
jobs:
  Coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -race -coverprofile=coverage.out -covermode=atomic
    - name: Upload results
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.out
